### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by NataliaPoletaeva** [vic778/js_capstone_project#39]
Great job on your project! Here is the feedback!

👍 good use of classes
👍 JS modules don't overlap and work properly

Keep going!

**Comment by kingqabil** [comment]
Greet work on your project 

good way of using modules 

Keep coding

**Comment by tmampa** [comment]
# Great job on getting your project approved

✔️ Great layout and markup
👌 Nice job on using ES6 syntax

## Congratulations and happy coding!!!!


![StandingOvationGIF](https://user-images.githubusercontent.com/67906597/148345582-91b9175b-1d49-4cff-ac5c-aacc56772cca.gif)

**Comment by cwaku** [comment]
@NataliaPoletaeva  @kingqabil @tmampa 

You are the best 💯 
Thank you for the awesome review.
![](https://media.giphy.com/media/pneG7YsDljrFo2nuFR/giphy.gif)
